#ifndef WEB_UI_H
#define WEB_UI_H

// Página HTML embarcada — gerada inline para não depender de SPIFFS
static const char WEB_UI_HTML[] =
"<!DOCTYPE html>"
"<html lang='pt-BR'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>UPS ESP32 Monitor</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:system-ui,sans-serif;background:#0f172a;color:#e2e8f0;padding:1rem}"
"h1{font-size:1.4rem;font-weight:700;color:#38bdf8;margin-bottom:.5rem}"
".subtitle{font-size:.8rem;color:#64748b;margin-bottom:1.5rem}"
".card{background:#1e293b;border-radius:.75rem;padding:1rem;margin-bottom:1rem}"
".card h2{font-size:.85rem;text-transform:uppercase;letter-spacing:.05em;color:#64748b;margin-bottom:.75rem}"
".info-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:.5rem}"
".info-item{background:#0f172a;border-radius:.5rem;padding:.6rem .8rem}"
".info-item .label{font-size:.7rem;color:#64748b;margin-bottom:.2rem}"
".info-item .value{font-size:1rem;font-weight:600;color:#f1f5f9}"
".info-item .unit{font-size:.7rem;color:#94a3b8}"
".badge{display:inline-block;padding:.2rem .6rem;border-radius:9999px;font-size:.7rem;font-weight:600}"
".badge.ok{background:#064e3b;color:#34d399}"
".badge.warn{background:#7c2d12;color:#fb923c}"
".badge.err{background:#450a0a;color:#f87171}"
"form{display:flex;flex-direction:column;gap:.75rem}"
"input[type=file]{background:#0f172a;border:1px solid #334155;border-radius:.5rem;padding:.5rem;color:#e2e8f0;width:100%}"
"button{background:#0ea5e9;color:#fff;border:none;border-radius:.5rem;padding:.6rem 1.2rem;font-size:.9rem;font-weight:600;cursor:pointer}"
"button:hover{background:#0284c7}"
"button:disabled{background:#334155;cursor:not-allowed}"
".progress-wrap{display:none;background:#0f172a;border-radius:9999px;height:.5rem;overflow:hidden}"
".progress-bar{height:100%;background:#0ea5e9;width:0%;transition:width .3s}"
".status-msg{font-size:.8rem;color:#94a3b8;min-height:1.2rem}"
"#conn-dot{display:inline-block;width:.6rem;height:.6rem;border-radius:50%;background:#64748b;margin-right:.4rem}"
"#conn-dot.on{background:#34d399}"
"#conn-dot.off{background:#f87171}"
"</style>"
"</head>"
"<body>"
"<h1>&#9889; UPS ESP32 Monitor</h1>"
"<div class='subtitle' id='info-line'>Carregando...</div>"

"<div class='card'>"
"<h2><span id='conn-dot'></span>Status do Nobreak</h2>"
"<div class='info-grid' id='metrics-grid'>"
"<div class='info-item'><div class='label'>Aguardando dados</div><div class='value'>--</div></div>"
"</div>"
"</div>"

"<div class='card'>"
"<h2>Atualizar Firmware (OTA)</h2>"
"<form id='ota-form'>"
"<input type='file' id='fw-file' accept='.bin' required>"
"<div class='progress-wrap' id='prog-wrap'><div class='progress-bar' id='prog-bar'></div></div>"
"<button type='submit' id='ota-btn'>&#8593; Enviar firmware</button>"
"<div class='status-msg' id='ota-status'></div>"
"</form>"
"</div>"

"<script>"
"const METRICS=["
"['Carga','power_out_percent','%'],"
"['V. Saída','voltage_out','V'],"
"['V. Entrada','voltage_in','V'],"
"['Corrente','current_out','A'],"
"['Pot. Saída','power_out','W'],"
"['Pot. Entrada','power_in','W'],"
"['Energia Saída','energy_out','kWh'],"
"['Energia Entrada','energy_in','kWh'],"
"['Temperatura','temperature','°C'],"
"['Bateria','battery_state','%'],"
"['V. Bateria','battery_voltage','V'],"
"['Frequência','frequency','Hz']"
"];"

"function renderMetrics(d){"
"const dot=document.getElementById('conn-dot');"
"if(!d.ups_connected){dot.className='off';}"
"else{dot.className='on';}"
"const grid=document.getElementById('metrics-grid');"
"grid.innerHTML=METRICS.map(([lbl,key,unit])=>"
"`<div class='info-item'><div class='label'>${lbl}</div>"
"<div class='value'>${(d[key] != null ? d[key] : '--').toLocaleString('pt-BR',{maximumFractionDigits:2})} "
"<span class='unit'>${unit}</span></div></div>`"
").join('');"
"}"

"async function fetchMetrics(){"
"try{"
"const r=await fetch('/api/metrics');"
"if(!r.ok)return;"
"const d=await r.json();"
"renderMetrics(d);"
"}catch(e){}"
"}"

"async function fetchInfo(){"
"try{"
"const r=await fetch('/api/info');"
"if(!r.ok)return;"
"const d=await r.json();"
"const el=document.getElementById('info-line');"
"el.textContent=`Versão ${d.version} · Partição ${d.partition} · Uptime ${Math.floor(d.uptime_s/60)}min`;"
"}catch(e){}"
"}"

"fetchMetrics();fetchInfo();"
"setInterval(fetchMetrics,5000);"
"setInterval(fetchInfo,30000);"

"document.getElementById('ota-form').addEventListener('submit',async e=>{"
"e.preventDefault();"
"const file=document.getElementById('fw-file').files[0];"
"if(!file)return;"
"const btn=document.getElementById('ota-btn');"
"const prog=document.getElementById('prog-wrap');"
"const bar=document.getElementById('prog-bar');"
"const msg=document.getElementById('ota-status');"
"btn.disabled=true;"
"prog.style.display='block';"
"msg.textContent='Enviando...';"
"const xhr=new XMLHttpRequest();"
"xhr.upload.onprogress=ev=>{"
"if(ev.lengthComputable){bar.style.width=(ev.loaded/ev.total*100)+'%';}"
"};"
"xhr.onload=()=>{"
"if(xhr.status===200){"
"msg.textContent='Concluído! O dispositivo vai reiniciar...';"
"bar.style.width='100%';"
"}else{"
"msg.textContent='Erro: '+xhr.responseText;"
"btn.disabled=false;"
"}"
"};"
"xhr.onerror=()=>{msg.textContent='Erro de conexão.';btn.disabled=false;};"
"xhr.open('POST','/ota');"
"xhr.setRequestHeader('Content-Type','application/octet-stream');"
"xhr.send(file);"
"});"
"</script>"
"</body></html>";

#endif // WEB_UI_H
