#ifndef WIFI_CONFIG_UI_H
#define WIFI_CONFIG_UI_H

// Página HTML do portal de configuração WiFi (AP mode)
// Sem trigraphs: não usar ?? em strings C
static const char WIFI_CONFIG_HTML[] =
"<!DOCTYPE html>"
"<html lang='pt-BR'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>UPS ESP32 - Configurar WiFi</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:system-ui,sans-serif;background:#0f172a;color:#e2e8f0;"
"display:flex;align-items:center;justify-content:center;min-height:100vh;padding:1rem}"
".card{background:#1e293b;border-radius:.75rem;padding:1.5rem;width:100%;max-width:360px}"
"h1{font-size:1.2rem;font-weight:700;color:#38bdf8;margin-bottom:.3rem}"
".sub{font-size:.8rem;color:#64748b;margin-bottom:1.5rem}"
"label{display:block;font-size:.75rem;color:#94a3b8;margin-bottom:.3rem}"
"input{width:100%;background:#0f172a;border:1px solid #334155;border-radius:.5rem;"
"padding:.6rem .8rem;color:#e2e8f0;font-size:.95rem;margin-bottom:1rem;outline:none}"
"input:focus{border-color:#38bdf8}"
"button{width:100%;background:#0ea5e9;color:#fff;border:none;border-radius:.5rem;"
"padding:.7rem;font-size:.95rem;font-weight:600;cursor:pointer}"
"button:hover{background:#0284c7}"
"button:disabled{background:#334155;cursor:not-allowed}"
".msg{margin-top:.75rem;font-size:.8rem;color:#94a3b8;text-align:center;min-height:1rem}"
".icon{font-size:2rem;margin-bottom:.75rem;display:block;text-align:center}"
"</style>"
"</head>"
"<body>"
"<div class='card'>"
"<span class='icon'>&#128246;</span>"
"<h1>Configurar WiFi</h1>"
"<p class='sub'>Conecte o dispositivo à sua rede local.</p>"
"<form id='f'>"
"<label for='s'>Nome da rede (SSID)</label>"
"<input id='s' name='ssid' type='text' maxlength='32' autocomplete='off' required placeholder='MinhaRede'>"
"<label for='p'>Senha</label>"
"<input id='p' name='password' type='password' maxlength='64' placeholder='senha'>"
"<button type='submit' id='btn'>Salvar e Conectar</button>"
"<p class='msg' id='msg'></p>"
"</form>"
"</div>"
"<script>"
"document.getElementById('f').addEventListener('submit',function(e){"
"e.preventDefault();"
"var btn=document.getElementById('btn');"
"var msg=document.getElementById('msg');"
"var ssid=document.getElementById('s').value.trim();"
"var pass=document.getElementById('p').value;"
"if(!ssid){msg.textContent='SSID obrigatorio.';return;}"
"btn.disabled=true;"
"msg.textContent='Salvando...';"
"var body='ssid='+encodeURIComponent(ssid)+'&password='+encodeURIComponent(pass);"
"var xhr=new XMLHttpRequest();"
"xhr.open('POST','/configure');"
"xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');"
"xhr.onload=function(){"
"if(xhr.status===200){"
"msg.textContent='Salvo! O dispositivo vai reiniciar e conectar na rede...';"
"}else{"
"msg.textContent='Erro: '+xhr.responseText;"
"btn.disabled=false;"
"}"
"};"
"xhr.onerror=function(){msg.textContent='Erro de conexao.';btn.disabled=false;};"
"xhr.send(body);"
"});"
"</script>"
"</body></html>";

#endif // WIFI_CONFIG_UI_H
